name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        fetch-depth: 0
        
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build the Docker image
       run: docker build ./src --tag kieftse/asmp2:$(date +%s) --tag kieftse/asmp2:latest

     - name: Push the Docker image
       run: docker push kieftse/asmp2:latest