name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       with:
        fetch-depth: 0
        
     - name: Install .NET Core
       uses: actions/setup-dotnet@v3
       with:
        dotnet-version: 7.0.x

     - name: Execute unit tests
       run: dotnet test ./src/Asmp2.Server.Tests.Unit/Asmp2.Server.Tests.Unit.csproj

     - name: Build the Docker image
       run: docker build ./src --tag kieftse/asmp2:$(date +%s) --tag kieftse/asmp2:latest

     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Push the Docker image
       run: docker push kieftse/asmp2:latest